// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import CollapsibleController from "./collapsible_controller"
application.register("collapsible", CollapsibleController)

import CommandPreviewController from "./command_preview_controller"
application.register("command-preview", CommandPreviewController)

import ConfigurationController from "./configuration_controller"
application.register("configuration", ConfigurationController)

import ConfirmDialogController from "./confirm_dialog_controller"
application.register("confirm-dialog", ConfirmDialogController)

import CronPreviewController from "./cron_preview_controller"
application.register("cron-preview", CronPreviewController)

import DialogController from "./dialog_controller"
application.register("dialog", DialogController)

import DismissibleController from "./dismissible_controller"
application.register("dismissible", DismissibleController)

import FilterController from "./filter_controller"
application.register("filter", FilterController)

import GaugeController from "./gauge_controller"
application.register("gauge", GaugeController)

import NotificationTestController from "./notification_test_controller"
application.register("notification-test", NotificationTestController)

import PatternListController from "./pattern_list_controller"
application.register("pattern-list", PatternListController)

import RepositoryTypeController from "./repository_type_controller"
application.register("repository-type", RepositoryTypeController)

import SearchController from "./search_controller"
application.register("search", SearchController)

import ServerAuthController from "./server_auth_controller"
application.register("server-auth", ServerAuthController)

import ServerTestController from "./server_test_controller"
application.register("server-test", ServerTestController)

import ServerPathController from "./server_path_controller"
application.register("server-path", ServerPathController)

import ThemeController from "./theme_controller"
application.register("theme", ThemeController)

import UnsavedChangesController from "./unsaved_changes_controller"
application.register("unsaved-changes", UnsavedChangesController)
