// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import CollapsibleController from "./collapsible_controller"
application.register("collapsible", CollapsibleController)

import ConfigurationController from "./configuration_controller"
application.register("configuration", ConfigurationController)

import ConfirmDialogController from "./confirm_dialog_controller"
application.register("confirm-dialog", ConfirmDialogController)

import ThemeController from "./theme_controller"
application.register("theme", ThemeController)

import DialogController from "./dialog_controller"
application.register("dialog", DialogController)

import RepositoryTypeController from "./repository_type_controller"
application.register("repository-type", RepositoryTypeController)

import ServerAuthController from "./server_auth_controller"
application.register("server-auth", ServerAuthController)
