version: 2

updates:
  - package-ecosystem: "bundler"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      dependencies-major:
        update-types:
          - "major"
        exclude-patterns:
          - "rubocop*"
      dependencies-minor-patch:
        update-types:
          - "minor"
          - "patch"
        exclude-patterns:
          - "rubocop*"
      rubocop-major:
        patterns:
          - "rubocop*"
        update-types:
          - "major"
      rubocop-minor-patch:
        patterns:
          - "rubocop*"
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      dependencies-major:
        update-types:
          - "major"
      dependencies-minor-patch:
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      dependencies:
        patterns:
          - "*"

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      dependencies-major:
        update-types:
          - "major"
      dependencies-minor-patch:
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      dependencies-major:
        update-types:
          - "major"
      dependencies-minor-patch:
        update-types:
          - "minor"
          - "patch"
