x-app: &app
  build: .
  image: rsync-ui:development
  volumes:
    - .:/app/
    - bundle:/usr/local/bundle/
    - npm:/app/node_modules/
    - ssh:/app/.ssh
    - storage:/app/tmp/storage
    - ./docker/pre_sync.sh:/usr/local/bin/pre_sync.sh:ro
    - ./docker/post_sync.sh:/usr/local/bin/post_sync.sh:ro
    - ./tmp/data/app:/data
  extra_hosts:
    - "nas:172.16.200.101"
    - "backup:172.16.200.102"
    - "backup.example.com:172.16.200.102"
    - "mirror:172.16.200.103"
    - "mirror.example.com:172.16.200.103"
  env_file:
    - .development.env
  networks:
    - default
    - ssh-servers

services:
  postgres:
    image: postgres:18
    volumes:
      - postgres:/var/lib/postgresql/18/docker/
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "127.0.0.1:5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 2s
      timeout: 5s
      retries: 30

  app:
    <<: *app
    hostname: app
    entrypoint: /app/docker/ssh/init-app.sh
    command: foreman start
    tty: true
    ports:
      - "127.0.0.1:3000:3000"
    depends_on:
      postgres:
        condition: service_healthy
      nas:
        condition: service_started
      backup:
        condition: service_started
      mirror:
        condition: service_started

  worker:
    <<: *app
    hostname: worker
    command: bin/jobs
    tty: true
    depends_on:
      postgres:
        condition: service_healthy

  nas:
    image: alpine:3.23
    volumes:
      - ./docker/ssh/init-nas.sh:/init.sh:ro
      - ./tmp/data/nas:/data
    command: /init.sh
    networks:
      ssh-servers:
        ipv4_address: 172.16.200.101

  backup:
    image: alpine:3.23
    volumes:
      - ./docker/ssh/init-backup.sh:/init.sh:ro
      - ./tmp/data/backup:/backup
    command: /init.sh
    networks:
      ssh-servers:
        ipv4_address: 172.16.200.102

  mirror:
    image: alpine:3.23
    volumes:
      - ./docker/ssh/init-mirror.sh:/init.sh:ro
      - ./tmp/data/mirror:/backup
    command: /init.sh
    networks:
      ssh-servers:
        ipv4_address: 172.16.200.103

volumes:
  postgres:
  bundle:
  npm:
  ssh:
  storage:
    driver_opts:
      type: tmpfs
      device: tmpfs
      o: "mode=755,uid=1000,gid=1000"

networks:
  default: {}
  ssh-servers:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.200.0/24
