x-app: &app
  build: .
  volumes:
    - .:/app/:cached
    - bundle:/usr/local/bundle/
    - npm:/app/node_modules/
    - ssh:/app/.ssh
    - ./docker/hosts:/etc/hosts:ro
    - ./docker/pre_sync.sh:/usr/local/bin/pre_sync.sh:ro
    - ./docker/post_sync.sh:/usr/local/bin/post_sync.sh:ro
    - ./tmp/data/app:/data:cached
  tmpfs:
    - /app/tmp/storage:mode=755,uid=1000,gid=1000
  depends_on:
    - postgres
  env_file:
    - .development.env
  networks:
    - default
    - ssh-servers

services:
  postgres:
    image: postgres:18
    volumes:
      - postgres:/var/lib/postgresql/18/docker/
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

  app:
    <<: *app
    entrypoint: /app/docker/ssh/init-app.sh
    command: foreman start
    tty: true
    ports:
      - "3000:3000"

  worker:
    <<: *app
    command: bin/jobs
    tty: true

  nas:
    image: alpine:3.23
    volumes:
      - ./docker/ssh/init-nas.sh:/init.sh:ro
      - ./tmp/data/nas:/data
    command: /init.sh
    networks:
      ssh-servers:
        ipv4_address: 172.16.200.101

  backup:
    image: alpine:3.23
    volumes:
      - ./docker/ssh/init-backup.sh:/init.sh:ro
      - ./tmp/data/backup:/backup
    command: /init.sh
    networks:
      ssh-servers:
        ipv4_address: 172.16.200.102

  mirror:
    image: alpine:3.23
    volumes:
      - ./docker/ssh/init-mirror.sh:/init.sh:ro
      - ./tmp/data/mirror:/backup
    command: /init.sh
    networks:
      ssh-servers:
        ipv4_address: 172.16.200.103

volumes:
  postgres:
  bundle:
  npm:
  ssh:

networks:
  default: {}
  ssh-servers:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.200.0/24
