---
- key: test.key
  type: string
  category: system
  default: "test_value"
- key: test.feature
  type: boolean
  category: features
  default: true
- key: test.dependent
  type: string
  category: system
  default: "dependent_value"
  dependencies:
    - test.feature
- key: test.transitive_dependent
  type: string
  category: system
  default: "transitive_dependent_value"
  dependencies:
    - test.dependent
- key: test.integer
  type: integer
  category: system
  default: 5
  minimum: 1
  maximum: 10
- key: test.integer_unbounded
  type: integer
  category: system
  default: 5
- key: test.float
  type: float
  category: system
  default: 5.0
  minimum: 1.0
  maximum: 10.0
- key: test.float_unbounded
  type: float
  category: system
  default: 5.0
- key: test.string_allowed
  type: string
  category: system
  default: "foo"
  allowed_values:
    - foo
    - bar
