---
- key: resource_usage
  type: boolean
  category: resource_usage
  default: true
- key: resource_usage.interval
  type: integer
  category: resource_usage
  default: 15
  minimum: 1
  maximum:
  dependencies:
    - resource_usage
- key: resource_usage.cpu_warning
  type: integer
  category: resource_usage
  default: 75
  minimum: 0
  maximum: 100
  dependencies:
    - resource_usage
- key: resource_usage.cpu_critical
  type: integer
  category: resource_usage
  default: 90
  minimum: 0
  maximum: 100
  dependencies:
    - resource_usage
- key: resource_usage.memory_warning
  type: integer
  category: resource_usage
  default: 80
  minimum: 0
  maximum: 100
  dependencies:
    - resource_usage
- key: resource_usage.memory_critical
  type: integer
  category: resource_usage
  default: 95
  minimum: 0
  maximum: 100
  dependencies:
    - resource_usage
- key: resource_usage.disk_warning
  type: integer
  category: resource_usage
  default: 80
  minimum: 0
  maximum: 100
  dependencies:
    - resource_usage
- key: resource_usage.disk_critical
  type: integer
  category: resource_usage
  default: 95
  minimum: 0
  maximum: 100
  dependencies:
    - resource_usage
- key: disk_size
  type: boolean
  category: resource_usage
  default: true
- key: disk_size.interval
  type: integer
  category: resource_usage
  default: 240
  minimum: 1
  maximum:
  dependencies:
    - disk_size
- key: scheduler
  type: boolean
  category: system
  default: true
- key: notifications
  type: boolean
  category: features
  default: true
- key: audits
  type: boolean
  category: features
  default: false
- key: audits.retention
  type: integer
  category: features
  default: 7
  minimum: 1
  maximum:
  dependencies:
    - audits
- key: hooks
  type: boolean
  category: features
  default: true
- key: hooks.timeout
  type: integer
  category: features
  default: 10
  minimum: 0
  maximum:
  dependencies:
    - hooks
- key: streaming
  type: boolean
  category: features
  default: true
- key: connectivity
  type: boolean
  category: connectivity
  default: true
- key: verify_host_key
  type: boolean
  category: connectivity
  default: true
  service: Configurations::VerifyHostKeyService
- key: connectivity.interval
  type: integer
  category: connectivity
  default: 5
  minimum: 1
  maximum:
  dependencies:
    - connectivity
- key: connectivity.threshold
  type: integer
  category: connectivity
  default: 15
  minimum: 1
  maximum:
  dependencies:
    - connectivity
- key: connectivity.ssh_key.algorithm
  type: string
  category: connectivity
  default: rsa
  allowed_values:
    - rsa
    - ed25519
    - ecdsa
- key: connectivity.ssh_key.length
  type: integer
  category: connectivity
  default: 2048
  minimum: 1024
  maximum:
- key: terminate_stuck_jobs
  type: boolean
  category: system
  default: true
- key: terminate_stuck_jobs.interval
  type: integer
  category: system
  default: 1
  minimum: 1
  maximum:
  dependencies:
    - terminate_stuck_jobs
- key: jobs.timeout
  type: integer
  category: system
  default: 480
  minimum: 0
  maximum:
- key: job_runs.retention
  type: integer
  category: system
  default: 31
  minimum: 1
  maximum:
