# frozen_string_literal: true

module Servers
  class SSHConfigService < ApplicationService
    SSH_DIR = Pathname.new(Dir.home).join(".ssh").freeze

    attr_reader :ssh_dir

    def initialize(ssh_dir: SSH_DIR)
      super()

      @ssh_dir = Pathname.new(ssh_dir)
    end

    def call
      # Create ~/.ssh if it doesn't exist
      ssh_dir.mkpath

      # Set correct permissions
      ssh_dir.chmod(0o700)

      servers = Server.all.to_a
      server_slugs = servers.map(&:slug)

      # Write private key, password, and known_hosts files
      servers.each do |server|
        if server.ssh_key.present?
          key_path = ssh_dir.join("#{server.slug}.pem")
          key_path.write(server.ssh_key)

          # Set correct permissions
          key_path.chmod(0o600)
        elsif server.password.present?
          pass_path = ssh_dir.join("#{server.slug}_password")
          pass_path.write(server.password)

          # Set correct permissions
          pass_path.chmod(0o600)
        end

        known_hosts_path = ssh_dir.join("#{server.slug}_known_hosts")

        if server.host_key.present?
          if server.port == 22
            known_hosts_path.write("#{server.host} #{server.host_key}\n")
          else
            known_hosts_path.write("[#{server.host}]:#{server.port} #{server.host_key}\n")
          end
        else
          known_hosts_path.write("")
        end

        known_hosts_path.chmod(0o600)
      end

      # Clean up orphan files
      ssh_dir.each_child do |path|
        basename = path.basename.to_s

        stem = if basename.end_with?(".pem")
                 basename.delete_suffix(".pem")
               elsif basename.end_with?("_password")
                 basename.delete_suffix("_password")
               elsif basename.end_with?("_known_hosts")
                 basename.delete_suffix("_known_hosts")
               else
                 next
               end

        next if server_slugs.include?(stem)

        path.delete
      end

      # Write config file
      lines = ["# Automatically generated by rsync-ui - DO NOT EDIT MANUALLY\n"]

      servers.each do |server|
        lines += [
          "Host #{server.slug}",
          "  HostName #{server.host}",
          "  Port #{server.port}",
          "  User #{server.username}",
          "  StrictHostKeyChecking yes",
          "  UserKnownHostsFile #{ssh_dir.join("#{server.slug}_known_hosts")}",
        ]

        if server.ssh_key.present?
          lines << "  IdentityFile #{ssh_dir.join("#{server.slug}.pem")}"
          lines << "  IdentitiesOnly yes"
        end

        lines << "\n"
      end

      # Atomically write config file
      file = ssh_dir.join("config.tmp")
      file.write(lines.join("\n"))
      file.chmod(0o600)

      File.rename(file, ssh_dir.join("config"))
    end
  end
end
