# frozen_string_literal: true

module Servers
  class SSHConfigService < ApplicationService
    SSH_DIR = Pathname.new(Dir.home).join(".ssh").freeze

    UUID_PATTERN = /\A[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}\z/i

    attr_reader :ssh_dir

    def initialize(ssh_dir: SSH_DIR)
      super()

      @ssh_dir = Pathname.new(ssh_dir)
    end

    def call
      # Create ~/.ssh if it doesn't exist
      ssh_dir.mkpath

      # Set correct permissions
      ssh_dir.chmod(0o700)

      servers = Server.all.to_a
      server_ids = servers.map { |s| s.id.to_s }

      # Write private key and password files
      servers.each do |server|
        if server.ssh_key.present?
          key_path = ssh_dir.join(server.id.to_s)
          key_path.write(server.ssh_key)

          # Set correct permissions
          key_path.chmod(0o600)
        elsif server.password.present?
          pass_path = ssh_dir.join("#{server.id}_password")
          pass_path.write(server.password)

          # Set correct permissions
          pass_path.chmod(0o600)
        end
      end

      # Clean up orphan private key and password files
      ssh_dir.each_child do |path|
        # Skip config file
        next if path.basename.to_s == "config"

        stem = path.basename.to_s.delete_suffix("_password")
        next unless UUID_PATTERN.match?(stem)

        # Skip servers that still exist
        next if server_ids.include?(stem)

        path.delete
      end

      # Write config file
      lines = ["# Automatically generated by rsync-ui - DO NOT EDIT MANUALLY\n"]

      servers.each do |server|
        lines += [
          "Host #{server.id}",
          "  HostName #{server.host}",
          "  Port #{server.port}",
          "  User #{server.username}",
          "  StrictHostKeyChecking no",
          "  UserKnownHostsFile /dev/null",
        ]

        if server.ssh_key.present?
          lines << "  IdentityFile #{ssh_dir.join(server.id.to_s)}"
          lines << "  IdentitiesOnly yes"
        end

        lines << "\n"
      end

      # Atomically write config file
      file = ssh_dir.join("config.tmp")
      file.write(lines.join("\n"))
      file.chmod(0o600)

      File.rename(file, ssh_dir.join("config"))
    end
  end
end
