# frozen_string_literal: true

module Servers
  class SSHConfigService < ApplicationService
    SSH_DIR = Pathname.new(Dir.home).join(".ssh").freeze

    # Environment variable pointing to the private key, set only while an SSH command is running
    IDENTITY_FILE_ENV = "RSYNC_UI_IDENTITY_FILE"

    attr_reader :ssh_dir

    def initialize(ssh_dir: SSH_DIR)
      super()

      @ssh_dir = Pathname.new(ssh_dir)
    end

    def call
      # Create ~/.ssh if it doesn't exist
      ssh_dir.mkpath

      # Set correct permissions
      ssh_dir.chmod(0o700)

      servers = Server.all.to_a
      server_slugs = servers.map(&:slug)

      # Write known_hosts files (private keys and passwords are only written when invoking SSH commands)
      servers.each do |server|
        next unless verify_host_key?

        known_hosts_path = ssh_dir.join("#{server.slug}_known_hosts")

        if server.host_key.present?
          if server.port == 22
            known_hosts_path.write("#{server.host} #{server.host_key}\n")
          else
            known_hosts_path.write("[#{server.host}]:#{server.port} #{server.host_key}\n")
          end
        else
          known_hosts_path.write("")
        end

        known_hosts_path.chmod(0o600)
      end

      # Clean up orphan known_hosts files, and private key and password files written by previous versions
      ssh_dir.each_child do |path|
        basename = path.basename.to_s

        next if basename.end_with?("_known_hosts") && server_slugs.include?(basename.delete_suffix("_known_hosts"))
        next unless basename.end_with?(".pem", "_password", "_known_hosts")

        path.delete
      end

      # Write config file
      lines = ["# Automatically generated by rsync-ui - DO NOT EDIT MANUALLY\n"]

      servers.each do |server|
        lines += [
          "Host #{server.slug}",
          "  HostName #{server.host}",
          "  Port #{server.port}",
          "  User #{server.username}",
        ]

        if verify_host_key?
          lines << "  StrictHostKeyChecking yes"
          lines << "  UserKnownHostsFile #{ssh_dir.join("#{server.slug}_known_hosts")}"
        else
          lines << "  StrictHostKeyChecking no"
          lines << "  UserKnownHostsFile #{File::NULL}"
        end

        if server.ssh_key.present?
          lines << "  IdentityFile ${#{IDENTITY_FILE_ENV}}"
          lines << "  IdentitiesOnly yes"
        end

        lines << "\n"
      end

      # Write config file and rename atomically
      Tempfile.open("config", ssh_dir) do |file|
        file.write(lines.join("\n"))
        file.flush
        file.chmod(0o600)

        File.rename(file.path, ssh_dir.join("config"))
      end
    end

    private

    def verify_host_key?
      Configuration.get("verify_host_key")
    end
  end
end
