x-app: &app
  image: ghcr.io/floriandejonckheere/rsync-ui:latest
  volumes:
    - storage:/app/storage
  networks:
    - rlyeh
  environment:
    RAILS_ENV: production
    RAILS_LOG_TO_STDOUT: 1
    RAILS_SERVE_STATIC_FILES: 1

    SECRET_KEY_BASE: ${SECRET_KEY_BASE}

    PG_HOST: ${PG_HOST}
    PG_USER: ${PG_USER}
    PG_PASSWORD: ${PG_PASSWORD}

    APP_HOST: ${APP_HOST}
    APP_EMAIL: ${APP_EMAIL}

    ADMIN_EMAIL: ${ADMIN_EMAIL}
    ADMIN_PASSWORD: ${ADMIN_PASSWORD}
  logging:
    driver: "json-file"
    options:
      max-file: "5"
      max-size: "1g"
      compress: "true"
  restart: unless-stopped

services:
  app:
    <<: *app
    labels:
      traefik.enable: "true"
      traefik.http.middlewares.rsync-ui-tls.redirectscheme.scheme: "https"

      traefik.http.routers.rsync-ui.rule: "Host(`rsync-ui.rlyeh.dejonckhee.re`)"
      traefik.http.routers.rsync-ui.entrypoints: "web"
      traefik.http.routers.rsync-ui.middlewares: "rsync-ui-tls"

      traefik.http.routers.rsync-ui-tls.rule: "Host(`rsync-ui.rlyeh.dejonckhee.re`)"
      traefik.http.routers.rsync-ui-tls.entrypoints: "websecure"
      traefik.http.routers.rsync-ui-tls.tls: "true"
      traefik.http.routers.rsync-ui-tls.tls.certresolver: "letsencrypt"

      traefik.http.services.rsync-ui.loadbalancer.server.port: "3000"

  postgres:
    image: postgres:18
    volumes:
      - postgres:/var/lib/postgresql/docker/
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

  migration:
    <<: *app
    command: bin/rails db:prepare && bin/rails database:seed:production
    restart: "no"

volumes:
  postgres:
  storage:

networks:
  rlyeh:
    external: true
    name: "rlyeh_default"
